version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    volumes:
      - ./public/json:/data
    ports:
      - "3000:3000"